#!/bin/bash

# pre-new --- Notmuch rules that run after notmuch new

# Actually delete emails with "deleted" tag. Taken from
# https://wiki.archlinux.org/title/Notmuch#Permanently_delete_emails.
notmuch search --output=files --format=text0 tag:deleted | xargs -r0 rm
